version: '3.8'

services:
  notion-api:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app:cached
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    expose:
      - "5678"

